# Generated by Django 2.2.14 on 2020-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_yubikey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationservice',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Use HTTPS API URLs by default?', verbose_name='Use SSL'),
        ),
    ]
